# TensorFlow Fundamentals

## importing tensorflow library

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


## Creating various kinds of tensors

### Using `tf.constant()` with the following information:
    1. Tensor Value
    2. Tensor Size
    3. Tensor Shape
    4. Tensor Datatype
    5. Tensor Dimension


In [2]:
scalar = tf.constant(5,dtype=tf.float32)

print("Scalar value:", scalar.numpy())
print("Scalar size:", tf.size(scalar).numpy())
print("Scalar shape:", scalar.shape)
print("Scalar datatype:", scalar.dtype)
print("Scalar dimensions:", scalar.ndim)

Scalar value: 5.0
Scalar size: 1
Scalar shape: ()
Scalar datatype: <dtype: 'float32'>
Scalar dimensions: 0


In [3]:
vector = tf.constant([10,7],dtype=tf.float32)

print("Vector value:", vector.numpy())
print("Vector size:", tf.size(vector).numpy())
print("Vector shape:", vector.shape)
print("Vector datatype:", vector.dtype)
print("Vector dimension:", vector.ndim)

Vector value: [10.  7.]
Vector size: 2
Vector shape: (2,)
Vector datatype: <dtype: 'float32'>
Vector dimension: 1


In [4]:
matrix = tf.constant([[3,5,6],
                      [1,2,3],
                      [5,6,7],
                      [8,9,5]],dtype=tf.float32)

print("Matrix value:\n", matrix.numpy())
print("Matrix size:", tf.size(matrix).numpy())
print("matrix shape:", matrix.shape)
print("Matrix datatype:", matrix.dtype)
print("Matrix dimension:", matrix.ndim)

Matrix value:
 [[3. 5. 6.]
 [1. 2. 3.]
 [5. 6. 7.]
 [8. 9. 5.]]
Matrix size: 12
matrix shape: (4, 3)
Matrix datatype: <dtype: 'float32'>
Matrix dimension: 2


In [5]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                      [[10,11,12],
                       [13,14,15],
                       [16,17,18]]],dtype=tf.float32)

print("Tensor valaue:\n", tensor.numpy())
print("Tensor size:", tf.size(tensor).numpy())
print("Tensor shape:", tensor.shape)
print("Tensor datatype:", tensor.dtype)
print("Tensor dimension:", tensor.ndim)

Tensor valaue:
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]]
Tensor size: 18
Tensor shape: (2, 3, 3)
Tensor datatype: <dtype: 'float32'>
Tensor dimension: 3


### Using `tf.Variable` with following information
    1. Tensor Value
    2. Tensor Size
    3. Tensor Shape
    4. Tensor Datatype
    5. Tensor Dimension

In [6]:
var_tensor = tf.Variable([[1,2,3,4],
                          [5,6,7,8]],dtype=tf.float32)

print("Variable tensor value:\n", var_tensor.numpy())
print("Variable tensor size:", tf.size(var_tensor).numpy())
print("Variable tensor shape:", var_tensor.shape)
print("Variable tensor datatype:", var_tensor.dtype)
print("Variable tensor dimension:", len(var_tensor.shape))

Variable tensor value:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
Variable tensor size: 8
Variable tensor shape: (2, 4)
Variable tensor datatype: <dtype: 'float32'>
Variable tensor dimension: 2


### Using `tf.random`
1. `.uniform`
2. `.normal`
3. `.set_seed`

In [7]:
uniform_tensor = tf.random.uniform([2,3,3], dtype=tf.int32, minval = 0, maxval = 10, seed = 42)

print("uniform tensor value:\n", uniform_tensor.numpy())
print("uniform tensor size:", tf.size(uniform_tensor).numpy())
print("uniform tensor shape:", uniform_tensor.shape)
print("uniform tensor datatype:", uniform_tensor.dtype)
print("unoform tensor dimension:", uniform_tensor.ndim)

uniform tensor value:
 [[[2 4 3]
  [9 1 8]
  [8 3 5]]

 [[6 6 9]
  [9 6 1]
  [7 5 2]]]
uniform tensor size: 18
uniform tensor shape: (2, 3, 3)
uniform tensor datatype: <dtype: 'int32'>
unoform tensor dimension: 3


In [8]:
normal_tensor = tf.random.normal([2,3,3], seed = 42)
normal_tensor

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[-0.28077507, -0.1377521 , -0.6763296 ],
        [ 0.02458041, -0.89358455, -0.82847327],
        [ 1.2068944 ,  1.3810157 , -1.4557977 ]],

       [[-0.24621388, -1.3608406 ,  1.0879604 ],
        [-0.3511659 , -0.5138534 ,  3.4117208 ],
        [ 0.05885482,  0.8918024 , -0.7528832 ]]], dtype=float32)>

In [9]:
tf.random.set_seed(42)
normal_tensor = tf.random.normal([3,2,2], seed = 10)
normal_tensor

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 0.520786  , -0.6879559 ],
        [ 0.3075672 ,  0.77124166]],

       [[-0.5088845 ,  0.7513481 ],
        [-2.6113875 , -0.95842814]],

       [[-0.11757406,  1.7861681 ],
        [-0.72368693, -0.7011757 ]]], dtype=float32)>