# TensorFlow Fundamentals

## importing tensorflow library

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


## Creating various kinds of tensors

### Using `tf.constant()` with the following information:
    1. Tensor Value
    2. Tensor Size
    3. Tensor Shape
    4. Tensor Datatype
    5. Tensor Dimension


In [2]:
scalar = tf.constant(5,dtype=tf.float32)

print("Scalar value:", scalar.numpy())
print("Scalar size:", tf.size(scalar).numpy())
print("Scalar shape:", scalar.shape)
print("Scalar datatype:", scalar.dtype)
print("Scalar dimensions:", scalar.ndim)

Scalar value: 5.0
Scalar size: 1
Scalar shape: ()
Scalar datatype: <dtype: 'float32'>
Scalar dimensions: 0


In [3]:
vector = tf.constant([10,7],dtype=tf.float32)

print("Vector value:", vector.numpy())
print("Vector size:", tf.size(vector).numpy())
print("Vector shape:", vector.shape)
print("Vector datatype:", vector.dtype)
print("Vector dimension:", vector.ndim)

Vector value: [10.  7.]
Vector size: 2
Vector shape: (2,)
Vector datatype: <dtype: 'float32'>
Vector dimension: 1


In [4]:
matrix = tf.constant([[3,5,6],
                      [1,2,3],
                      [5,6,7],
                      [8,9,5]],dtype=tf.float32)

print("Matrix value:\n", matrix.numpy())
print("Matrix size:", tf.size(matrix).numpy())
print("matrix shape:", matrix.shape)
print("Matrix datatype:", matrix.dtype)
print("Matrix dimension:", matrix.ndim)

Matrix value:
 [[3. 5. 6.]
 [1. 2. 3.]
 [5. 6. 7.]
 [8. 9. 5.]]
Matrix size: 12
matrix shape: (4, 3)
Matrix datatype: <dtype: 'float32'>
Matrix dimension: 2


In [5]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                      [[10,11,12],
                       [13,14,15],
                       [16,17,18]]],dtype=tf.float32)

print("Tensor valaue:\n", tensor.numpy())
print("Tensor size:", tf.size(tensor).numpy())
print("Tensor shape:", tensor.shape)
print("Tensor datatype:", tensor.dtype)
print("Tensor dimension:", tensor.ndim)

Tensor valaue:
 [[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]]
Tensor size: 18
Tensor shape: (2, 3, 3)
Tensor datatype: <dtype: 'float32'>
Tensor dimension: 3


### Using `tf.Variable` with following information
    1. Tensor Value
    2. Tensor Size
    3. Tensor Shape
    4. Tensor Datatype
    5. Tensor Dimension

In [6]:
var_tensor = tf.Variable([[1,2,3,4],
                          [5,6,7,8]],dtype=tf.float32)

print("Variable tensor value:\n", var_tensor.numpy())
print("Variable tensor size:", tf.size(var_tensor).numpy())
print("Variable tensor shape:", var_tensor.shape)
print("Variable tensor datatype:", var_tensor.dtype)
print("Variable tensor dimension:", len(var_tensor.shape))

Variable tensor value:
 [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
Variable tensor size: 8
Variable tensor shape: (2, 4)
Variable tensor datatype: <dtype: 'float32'>
Variable tensor dimension: 2


### Using `tf.random`
1. `.uniform`
2. `.normal`
3. `.set_seed`

In [7]:
uniform_tensor = tf.random.uniform([2,3,3], dtype=tf.int32, minval = 0, maxval = 10, seed = 42)

print("uniform tensor value:\n", uniform_tensor.numpy())
print("uniform tensor size:", tf.size(uniform_tensor).numpy())
print("uniform tensor shape:", uniform_tensor.shape)
print("uniform tensor datatype:", uniform_tensor.dtype)
print("unoform tensor dimension:", uniform_tensor.ndim)

uniform tensor value:
 [[[2 4 3]
  [9 1 8]
  [8 3 5]]

 [[6 6 9]
  [9 6 1]
  [7 5 2]]]
uniform tensor size: 18
uniform tensor shape: (2, 3, 3)
uniform tensor datatype: <dtype: 'int32'>
unoform tensor dimension: 3


In [8]:
normal_tensor = tf.random.normal([2,3,3], seed = 42)

print("Normal tensor  value:\n", normal_tensor.numpy())
print("Normal tensor size:", tf.size(normal_tensor).numpy())
print("Normal tensor shape:", normal_tensor.shape)
print("Normal tensor datatype:", normal_tensor.dtype)
print("Normal tensor dimension:", normal_tensor.ndim)

Normal tensor  value:
 [[[-0.28077507 -0.1377521  -0.6763296 ]
  [ 0.02458041 -0.89358455 -0.82847327]
  [ 1.2068944   1.3810157  -1.4557977 ]]

 [[-0.24621388 -1.3608406   1.0879604 ]
  [-0.3511659  -0.5138534   3.4117208 ]
  [ 0.05885482  0.8918024  -0.7528832 ]]]
Normal tensor size: 18
Normal tensor shape: (2, 3, 3)
Normal tensor datatype: <dtype: 'float32'>
Normal tensor dimension: 3


In [9]:
tf.random.set_seed(42)
normal_tensor = tf.random.normal([3,2,2], seed = 10)

print("Normal tensor  value:\n", normal_tensor.numpy())
print("Normal tensor size:", tf.size(normal_tensor).numpy())
print("Normal tensor shape:", normal_tensor.shape)
print("Normal tensor datatype:", normal_tensor.dtype)
print("Normal tensor dimension:", normal_tensor.ndim)

Normal tensor  value:
 [[[ 0.520786   -0.6879559 ]
  [ 0.3075672   0.77124166]]

 [[-0.5088845   0.7513481 ]
  [-2.6113875  -0.95842814]]

 [[-0.11757406  1.7861681 ]
  [-0.72368693 -0.7011757 ]]]
Normal tensor size: 12
Normal tensor shape: (3, 2, 2)
Normal tensor datatype: <dtype: 'float32'>
Normal tensor dimension: 3


### Using
1. `tf.zeros()`
2. `tf.ones()`

In [10]:
z = tf.zeros([3,2,3],dtype=tf.int32)
z

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=int32)>

In [11]:
o = tf.ones([2,3,4],dtype=tf.int32)
o

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)>

## Manipulating tensors

### Using:
1. `tf.random.shuffle()`
2. `tf.transpose()`
3. `tf.reshape()`

In [12]:
tf.random.set_seed(42)
x = tf.random.uniform([2,3,3], dtype=tf.int32, minval = 0, maxval = 50, seed = 1)
x

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 9, 45,  0],
        [36, 19, 30],
        [42, 32, 25]],

       [[11, 16, 36],
        [47,  3,  4],
        [25, 41,  0]]], dtype=int32)>

In [13]:
tf.random.shuffle(x)

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[11, 16, 36],
        [47,  3,  4],
        [25, 41,  0]],

       [[ 9, 45,  0],
        [36, 19, 30],
        [42, 32, 25]]], dtype=int32)>

In [14]:
tf.transpose(x)

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[ 9, 11],
        [36, 47],
        [42, 25]],

       [[45, 16],
        [19,  3],
        [32, 41]],

       [[ 0, 36],
        [30,  4],
        [25,  0]]], dtype=int32)>

In [15]:
print(3*3*2)
print(2*9)
print(6*3)

18
18
18


In [16]:
tf.reshape(x,[3,6])

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[ 9, 45,  0, 36, 19, 30],
       [42, 32, 25, 11, 16, 36],
       [47,  3,  4, 25, 41,  0]], dtype=int32)>

### Using
1. `+` or `tf.add()` or `tf.math.add()`
2. `-` or `tf.subtract()` or `tf.math.subtract()`
3. `*` or `tf.multiply()` or `tf.math.multiply()`
4. `/` or `tf.divide()` or `tf.math.multiply()`

In [17]:
tf.random.set_seed(42)
x = tf.random.uniform([3,3], dtype = tf.int32, minval = 0, maxval = 100, seed = 42)

print("original tensor:\n", x.numpy())
print("\nusing tf.add():\n", tf.add(x,10).numpy())
print("\nusing tf.math.add()\n", tf.math.add(x,10).numpy())
print("\nusing `+`:\n", (x+10).numpy())

print("\nusing tf.subtract():\n", tf.subtract(x,10).numpy())
print("\nusing tf.math.subtract():\n", tf.math.subtract(x,10).numpy())
print("\nusing `-`:\n", (x-10).numpy())

print("\nusing tf.multiply():\n", tf.multiply(x,10).numpy())
print("\nusing tf.math.multiply():\n", tf.math.multiply(x,10).numpy())
print("\nusing `*`:\n", (x*10).numpy())

print("\nusing tf.divide():\n", tf.divide(x,10).numpy())
print("\nusing tf.math.divide():\n", tf.math.divide(x,10).numpy())
print("\nusing `/`:\n", tf.divide(x,10).numpy())

original tensor:
 [[33 38 30]
 [74  8 41]
 [53 73 42]]

using tf.add():
 [[43 48 40]
 [84 18 51]
 [63 83 52]]

using tf.math.add()
 [[43 48 40]
 [84 18 51]
 [63 83 52]]

using `+`:
 [[43 48 40]
 [84 18 51]
 [63 83 52]]

using tf.subtract():
 [[23 28 20]
 [64 -2 31]
 [43 63 32]]

using tf.math.subtract():
 [[23 28 20]
 [64 -2 31]
 [43 63 32]]

using `-`:
 [[23 28 20]
 [64 -2 31]
 [43 63 32]]

using tf.multiply():
 [[330 380 300]
 [740  80 410]
 [530 730 420]]

using tf.math.multiply():
 [[330 380 300]
 [740  80 410]
 [530 730 420]]

using `*`:
 [[330 380 300]
 [740  80 410]
 [530 730 420]]

using tf.divide():
 [[3.3 3.8 3. ]
 [7.4 0.8 4.1]
 [5.3 7.3 4.2]]

using tf.math.divide():
 [[3.3 3.8 3. ]
 [7.4 0.8 4.1]
 [5.3 7.3 4.2]]

using `/`:
 [[3.3 3.8 3. ]
 [7.4 0.8 4.1]
 [5.3 7.3 4.2]]


### Using `tf.abs()`

In [18]:
tf.random.set_seed(42)
x = tf.random.uniform([2,3,4],dtype=tf.int32,minval=-100,maxval=100,seed=42)
x

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[-67,  38,  30,  74],
        [  8,  41,  53, -27],
        [-58, -95,  76,  44]],

       [[ -7,  67, -94,  66],
        [-58, -57,  91, -82],
        [-54,  90, -86,  76]]], dtype=int32)>

In [19]:
tf.abs(x)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[67, 38, 30, 74],
        [ 8, 41, 53, 27],
        [58, 95, 76, 44]],

       [[ 7, 67, 94, 66],
        [58, 57, 91, 82],
        [54, 90, 86, 76]]], dtype=int32)>

## Finding the max, min, mean, sum, variance, std dev

### Using
1. `tf.reduce_max()`
2. `tf.reduce_min()`
3. `tf.reduce_mean()`
4. `tf.reduce_sum()`
5. `tf.math.reduce_variance()`
6. `tf.math.reduce_std()`

In [20]:
tf.random.set_seed(42)
x = tf.random.uniform([3,3,3],dtype=tf.int32,minval=-100,maxval=100,seed=42)
x

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[-67,  38,  30],
        [ 74,   8,  41],
        [ 53, -27, -58]],

       [[-95,  76,  44],
        [ -7,  67, -94],
        [ 66, -58, -57]],

       [[ 91, -82, -54],
        [ 90, -86,  76],
        [ -9,  -9,  46]]], dtype=int32)>

In [21]:
print("tensor maximum value:", tf.reduce_max(x).numpy())
print("tensor minimum value:", tf.reduce_min(x).numpy())
print("tensor mean value:", tf.reduce_mean(x).numpy())
print("tensor sum of elements:", tf.reduce_sum(x).numpy())
print("tensor variance:", tf.math.reduce_variance(tf.cast(x,dtype=tf.float32)).numpy())
print("tensor standard deviation:", tf.math.reduce_std(tf.cast(x,dtype=tf.float32)).numpy())

tensor maximum value: 91
tensor minimum value: -95
tensor mean value: 3
tensor sum of elements: 97
tensor variance: 3820.6858
tensor standard deviation: 61.811695


## Manipulating of tensor indeces and elements

### Using 
1. `[:]`
2. `tf.argmin()`
3. `tf.argmax()`

In [22]:
import numpy as np
tf.random.set_seed(42)
x = np.arange(1,100,2)
x = tf.constant(x)
#x = tf.reshape(x,[5,5])
y = x[10:]
z = x[:10]

y = tf.reshape(y,[10,4])
z = tf.reshape(z,[1,10])

matmul = tf.matmul(z,y)

x.numpy(), y.numpy(),z.numpy(),y.ndim,z.ndim, y.shape, z.shape , matmul.numpy(), matmul.shape, matmul.ndim

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
        69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),
 array([[21, 23, 25, 27],
        [29, 31, 33, 35],
        [37, 39, 41, 43],
        [45, 47, 49, 51],
        [53, 55, 57, 59],
        [61, 63, 65, 67],
        [69, 71, 73, 75],
        [77, 79, 81, 83],
        [85, 87, 89, 91],
        [93, 95, 97, 99]]),
 array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]]),
 2,
 2,
 TensorShape([10, 4]),
 TensorShape([1, 10]),
 array([[7020, 7220, 7420, 7620]]),
 TensorShape([1, 4]),
 2)

In [23]:
print("Maximum element across y-axis or 1-axis:\n", tf.reshape(tf.argmax(y,1),[10,1]).numpy()) 
print("Maximum element across x-axis or 0-axis:\n", tf.argmax(y,0).numpy())

Maximum element across y-axis or 1-axis:
 [[3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]
 [3]]
Maximum element across x-axis or 0-axis:
 [9 9 9 9]


## dot multiplication of tensors

### Using
1. `tf.matmul()`
2. `tf.tensordot()`
3. `@`

In [24]:
import numpy as np
tf.random.set_seed(42)

x = tf.random.uniform([3,3],dtype=tf.int32,minval=0,maxval=100,seed=42)
y = tf.range(1,6+1)
y = tf.reshape(y,[2,3])
z = np.arange(0,27)
z = tf.reshape(tf.constant(z),[3,3,3])
x, y, z

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[33, 38, 30],
        [74,  8, 41],
        [53, 73, 42]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3, 3), dtype=int64, numpy=
 array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])>)

In [25]:
y = tf.reshape(y,[3,2])
matmul = tf.matmul(x,y)
tensordot = tf.tensordot(x,y,1)
matmul, tensordot, x@y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[297, 398],
        [303, 426],
        [482, 650]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[297, 398],
        [303, 426],
        [482, 650]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[297, 398],
        [303, 426],
        [482, 650]], dtype=int32)>)

## Removing 1-dimension of tensor

### using `tf.squeeze()`

In [26]:
tf.random.set_seed(42)
x = np.arange(-8,100,2)
x = tf.constant(x)
x = tf.reshape(x,[1,1,1,2,1,3,1,3,3])
x

<tf.Tensor: shape=(1, 1, 1, 2, 1, 3, 1, 3, 3), dtype=int64, numpy=
array([[[[[[[[[-8, -6, -4],
              [-2,  0,  2],
              [ 4,  6,  8]]],


            [[[10, 12, 14],
              [16, 18, 20],
              [22, 24, 26]]],


            [[[28, 30, 32],
              [34, 36, 38],
              [40, 42, 44]]]]],




          [[[[[46, 48, 50],
              [52, 54, 56],
              [58, 60, 62]]],


            [[[64, 66, 68],
              [70, 72, 74],
              [76, 78, 80]]],


            [[[82, 84, 86],
              [88, 90, 92],
              [94, 96, 98]]]]]]]]])>

In [27]:
tf.squeeze(x)

<tf.Tensor: shape=(2, 3, 3, 3), dtype=int64, numpy=
array([[[[-8, -6, -4],
         [-2,  0,  2],
         [ 4,  6,  8]],

        [[10, 12, 14],
         [16, 18, 20],
         [22, 24, 26]],

        [[28, 30, 32],
         [34, 36, 38],
         [40, 42, 44]]],


       [[[46, 48, 50],
         [52, 54, 56],
         [58, 60, 62]],

        [[64, 66, 68],
         [70, 72, 74],
         [76, 78, 80]],

        [[82, 84, 86],
         [88, 90, 92],
         [94, 96, 98]]]])>

## One_hot encoding of tensors

### Using ` tf.one_hot()`

In [28]:
index = [[0,1,2,3],
         [1,3,0,2]]
depth = 4
one_hot = tf.one_hot(index, depth, on_value = 1, off_value = 0,dtype = tf.int32)
one_hot

<tf.Tensor: shape=(2, 4, 4), dtype=int32, numpy=
array([[[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]],

       [[0, 1, 0, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 0, 1, 0]]], dtype=int32)>