# TensorFlow Fundamentals

## importing tensorflow library

In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


## Creating various kinds of tensors

### Using `tf.constant()` with the following information:
    1. Tensor Value
    2. Tensor Size
    3. Tensor Shape
    4. Tensor Datatype
    5. Tensor Dimension


In [2]:
scalar = tf.constant([5],dtype=tf.float32)

print("Scalar value:", scalar.numpy())
print("Scalar size:", tf.size(scalar).numpy())
print("Scalar shape:", scalar.shape)
print("Scalar datatype:", scalar.dtype)
print("Scalar dimensions:", scalar.ndim)

Scalar value: [5.]
Scalar size: 1
Scalar shape: (1,)
Scalar datatype: <dtype: 'float32'>
Scalar dimensions: 1


In [3]:
vector = tf.constant([[10,7],
                      [3,4]],dtype=tf.float32)

print("Vector value:", vector.numpy())
print("Vector size:", tf.size(vector).numpy())
print("Vector shape:", vector.shape)
print("Vector datatype:", vector.dtype)
print("Vector dimension:", vector.ndim)

Vector value: [[10.  7.]
 [ 3.  4.]]
Vector size: 4
Vector shape: (2, 2)
Vector datatype: <dtype: 'float32'>
Vector dimension: 2


In [4]:
matrix = tf.constant([[[3,5,6],
                       [1,2,3]],
                      [[5,6,7],
                       [8,9,5]]],dtype=tf.float32)

print("Matrix value:\n", matrix.numpy())
print("Matrix size:", tf.size(matrix).numpy())
print("matrix shape:", matrix.shape)
print("Matrix datatype:", matrix.dtype)
print("Matrix dimension:", matrix.ndim)

Matrix value:
 [[[3. 5. 6.]
  [1. 2. 3.]]

 [[5. 6. 7.]
  [8. 9. 5.]]]
Matrix size: 12
matrix shape: (2, 2, 3)
Matrix datatype: <dtype: 'float32'>
Matrix dimension: 3
